import TelegramBot from 'node-telegram-bot-api';
import { db, audit, acquireLock, releaseLock } from './db.js';
import { COMMON_COLORS, validatePalette } from './colors.js';
import { assignGroups, createGroupGames, seedDemo, clearDemo, qualificationPlan, createKnockout, advanceKnockout, setTieOrder } from './tournament.js';

const admins=new Set((process.env.TELEGRAM_ADMIN_IDS||'').split(',').map(x=>x.trim()).filter(Boolean));
const states=new Map();
const kb=inline_keyboard=>({reply_markup:{inline_keyboard}});
const back=(text,data)=>[{text:`⬅️ ${text}`,callback_data:data}];
const mainMenu=kb([[{text:'🖥 Seite verwalten',callback_data:'page'}],[{text:'👥 Teams & Gruppen',callback_data:'teams'},{text:'🏆 Spiele',callback_data:'games'}],[{text:'🌳 K.-o.-Phase',callback_data:'ko'}]]);
const pageMenu=kb([[{text:'🚀 Onboarding',callback_data:'onboarding'}],[{text:'🎨 Farben / Branding',callback_data:'page_branding'},{text:'🖼 Seitenlogo',callback_data:'page_logo'}],[{text:'📝 Texte verwalten',callback_data:'page_texts'}],[{text:'🎮 Spielablauf',callback_data:'page_flow'},{text:'🤝 Sponsoren',callback_data:'page_sponsors'}],[{text:'🧪 Testdaten',callback_data:'page_demo'}],[...back('Hauptmenü','main')]]);
const textMenu=kb([[{text:'🏷 Seitentitel',callback_data:'text_title'},{text:'💬 Beschreibung',callback_data:'text_description'}],[{text:'📢 Laufbanner',callback_data:'text_ticker'},{text:'📜 Regelwerk',callback_data:'text_rules'}],[...back('Seite verwalten','page')]]);
const colorButtons=(slot)=>kb([...COMMON_COLORS.map(([name,hex])=>[{text:`${name}  ${hex}`,callback_data:`color:${slot}:${hex}`}]),back('Seite verwalten','page')]);
async function begin(bot,chat,id,scope,state,text,options){const l=await acquireLock(scope,id);if(!l.ok)return bot.sendMessage(chat,'⚠️ Ein anderer Administrator bearbeitet diesen Bereich gerade.');states.set(id,{...state,scope});return bot.sendMessage(chat,text,options)}
async function done(id){const s=states.get(id);if(s?.scope)await releaseLock(s.scope,id);states.delete(id)}
async function photo(bot,m){const p=m.photo?.at(-1);if(!p)return null;const r=await fetch(await bot.getFileLink(p.file_id));const b=Buffer.from(await r.arrayBuffer());if(b.length>2e6)throw Error('large');return`data:image/jpeg;base64,${b.toString('base64')}`}
const eh=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function entityTags(e){if(e.type==='bold')return['<strong>','</strong>'];if(e.type==='italic')return['<em>','</em>'];if(e.type==='underline')return['<u>','</u>'];if(e.type==='strikethrough')return['<s>','</s>'];if(e.type==='code')return['<code>','</code>'];if(e.type==='pre')return['<pre>','</pre>'];if(e.type==='text_link'&&/^https?:\/\//i.test(e.url||''))return[`<a href="${eh(e.url)}">`,'</a>'];return['','']}
function telegramToHtml(text,entities=[]){const opens=new Map(),closes=new Map();for(const e of entities){const[o,c]=entityTags(e);if(!o)continue;(opens.get(e.offset)||opens.set(e.offset,[]).get(e.offset)).push({...e,tag:o});(closes.get(e.offset+e.length)||closes.set(e.offset+e.length,[]).get(e.offset+e.length)).push({...e,tag:c})}let out='';for(let i=0;i<=text.length;i++){for(const e of(closes.get(i)||[]).sort((a,b)=>b.offset-a.offset))out+=e.tag;for(const e of(opens.get(i)||[]).sort((a,b)=>b.length-a.length))out+=e.tag;if(i<text.length)out+=eh(text[i])}return out.replaceAll('\n','<br>')}

export function startBot(){if(!process.env.TELEGRAM_BOT_TOKEN)return;const bot=new TelegramBot(process.env.TELEGRAM_BOT_TOKEN,{polling:true});const ok=(m,u=m.from)=>m.chat?.type==='private'&&admins.has(String(u?.id));const home=(chat,text='FTB Administration')=>bot.sendMessage(chat,text,mainMenu);
bot.onText(/\/start/,async m=>{if(!ok(m))return bot.sendMessage(m.chat.id,'Kein Zugriff.');const s=(await db.query('SELECT onboarding_done FROM settings WHERE id=1')).rows[0];return s?.onboarding_done?home(m.chat.id):bot.sendMessage(m.chat.id,'Willkommen bei FTB. Starte mit der Ersteinrichtung.',kb([[{text:'🚀 Onboarding starten',callback_data:'onboarding'}],[{text:'Später',callback_data:'main'}]]))});
bot.on('callback_query',async q=>{const m=q.message,id=q.from.id,d=q.data;if(!ok(m,q.from))return;await bot.answerCallbackQuery(q.id);try{
if(d==='main')return home(m.chat.id);if(d==='page')return bot.sendMessage(m.chat.id,'Seite verwalten',pageMenu);if(d==='page_texts')return bot.sendMessage(m.chat.id,'Texte verwalten',textMenu);
if(d==='onboarding')return begin(bot,m.chat.id,id,'page',{step:'onboard_title'},'Seitentitel eingeben:');
if(d==='page_branding')return bot.sendMessage(m.chat.id,'Primärfarbe wählen:',colorButtons('primary'));
if(d.startsWith('color:')){const[,slot,hex]=d.split(':');const s=(await db.query('SELECT primary_color,secondary_color,accent_color FROM settings WHERE id=1')).rows[0];const cols={primary:s.primary_color,secondary:s.secondary_color,accent:s.accent_color,[slot]:hex};const v=validatePalette(cols.primary,cols.secondary,cols.accent);if(!v.ok)return bot.sendMessage(m.chat.id,v.error,pageMenu);await db.query(`UPDATE settings SET ${slot==='primary'?'primary_color':slot==='secondary'?'secondary_color':'accent_color'}=$1,version=version+1 WHERE id=1`,[hex]);if(slot==='primary')return bot.sendMessage(m.chat.id,'Sekundärfarbe wählen:',colorButtons('secondary'));if(slot==='secondary')return bot.sendMessage(m.chat.id,'Tertiärfarbe wählen:',colorButtons('accent'));return bot.sendMessage(m.chat.id,'Farben gespeichert.',pageMenu)}
if(d==='page_logo')return begin(bot,m.chat.id,id,'page',{step:'site_logo'},'Neues Seitenlogo als Foto senden. /remove entfernt es.',kb([back('Seite verwalten','page')]));
if(d==='page_flow')return bot.sendMessage(m.chat.id,'Wie soll das Finale gespielt werden?',kb([[{text:'1 Entscheidungsspiel',callback_data:'flow:single'}],[{text:'Best of Three',callback_data:'flow:bo3'}],back('Seite verwalten','page')]));
if(d.startsWith('flow:')){await db.query('UPDATE settings SET final_mode=$1,version=version+1 WHERE id=1',[d.split(':')[1]]);return bot.sendMessage(m.chat.id,'Spielablauf gespeichert.',pageMenu)}
if(d==='text_title')return begin(bot,m.chat.id,id,'page',{step:'title'},'Neuen Seitentitel senden:',kb([back('Texte','page_texts')]));if(d==='text_description')return begin(bot,m.chat.id,id,'page',{step:'description'},'Beschreibung senden oder /remove:',kb([back('Texte','page_texts')]));if(d==='text_ticker')return begin(bot,m.chat.id,id,'page',{step:'ticker'},'Laufbanner senden. „aus“ deaktiviert es:',kb([back('Texte','page_texts')]));
if(d==='text_rules')return begin(bot,m.chat.id,id,'rules',{step:'rules_collect',html:[],plain:[]},'Regelwerk als formatierte Telegram-Nachrichten senden. Mehrere Nachrichten sind möglich.',kb([[{text:'❌ Verwerfen',callback_data:'rules_cancel'}],back('Texte','page_texts')]));
if(d==='rules_save'){const s=states.get(id);if(!s||s.step!=='rules_collect')return;await db.query('UPDATE settings SET rules=$1,rules_html=$2,version=version+1 WHERE id=1',[s.plain.join('\n\n').slice(0,60000),s.html.join('<br><br>').slice(0,120000)]);await done(id);return bot.sendMessage(m.chat.id,'Regelwerk gespeichert.',textMenu)}if(d==='rules_cancel'){await done(id);return bot.sendMessage(m.chat.id,'Regelbearbeitung verworfen.',textMenu)}
if(d==='page_demo')return bot.sendMessage(m.chat.id,'Testdaten',kb([[{text:'Erstellen',callback_data:'demo_seed'},{text:'Löschen',callback_data:'demo_clear'}],back('Seite verwalten','page')]));if(d==='demo_seed'){await seedDemo();return bot.sendMessage(m.chat.id,'Testdaten erstellt.',pageMenu)}if(d==='demo_clear'){await clearDemo();return bot.sendMessage(m.chat.id,'Testdaten gelöscht.',pageMenu)}
if(d==='page_sponsors')return showSponsors(bot,m.chat.id);if(d==='sponsor_add')return begin(bot,m.chat.id,id,'sponsors',{step:'sponsor_name'},'Name des Sponsors:',kb([back('Sponsoren','page_sponsors')]));if(d.startsWith('sponsor:')){const sid=+d.split(':')[1],s=(await db.query('SELECT * FROM sponsors WHERE id=$1',[sid])).rows[0];if(!s)return showSponsors(bot,m.chat.id);return bot.sendMessage(m.chat.id,`Sponsor: ${s.name}`,kb([[{text:'🗑 Entfernen',callback_data:`sponsor_delete:${sid}`}],back('Sponsoren','page_sponsors')]))}if(d.startsWith('sponsor_delete:')){await db.query('DELETE FROM sponsors WHERE id=$1',[+d.split(':')[1]]);return showSponsors(bot,m.chat.id)}
if(d==='teams')return showTeams(bot,m.chat.id);if(d==='team_add')return begin(bot,m.chat.id,id,'teams',{step:'team_name'},'Teamname:',kb([back('Teams','teams')]));if(d==='team_manage')return chooseTeam(bot,m.chat.id,'Team verwalten:','tm:');if(d.startsWith('tm:'))return teamManage(bot,m.chat.id,+d.split(':')[1]);if(d.startsWith('team_dq:')){const tid=+d.split(':')[1];await db.query('UPDATE teams SET disqualified=NOT disqualified,version=version+1 WHERE id=$1',[tid]);return teamManage(bot,m.chat.id,tid)}if(d.startsWith('team_group:'))return begin(bot,m.chat.id,id,'teams',{step:'manual_group',teamId:+d.split(':')[1]},'Neue Gruppe, „-“ für keine:',kb([back('Team','tm:'+d.split(':')[1])]));if(d.startsWith('team_logo:'))return begin(bot,m.chat.id,id,'teams',{step:'team_logo_edit',teamId:+d.split(':')[1]},'Neues Teamlogo oder /remove:',kb([back('Team','tm:'+d.split(':')[1])]));if(d==='groups_auto')return begin(bot,m.chat.id,id,'teams',{step:'group_count'},'Anzahl Gruppen, 1 bis 26:',kb([back('Teams','teams')]));if(d==='groups_manual')return chooseTeam(bot,m.chat.id,'Team für Gruppenzuordnung:','team_group:');if(d==='groups_games'){try{const r=await createGroupGames();return bot.sendMessage(m.chat.id,`${r.games} Gruppenspiele erstellt.`,mainMenu)}catch(e){return bot.sendMessage(m.chat.id,e.message==='group_games_exist'?'Gruppenspiele existieren bereits.':'Fehler beim Erzeugen.',mainMenu)}}
if(d==='games')return showGames(bot,m.chat.id);if(d.startsWith('res:')){const gid=+d.split(':')[1],g=(await db.query(`SELECT g.version,h.id hid,h.name home,a.id aid,a.name away FROM games g JOIN teams h ON h.id=g.home_team_id JOIN teams a ON a.id=g.away_team_id WHERE g.id=$1`,[gid])).rows[0];if(!g)return;return bot.sendMessage(m.chat.id,'Spiel aktualisieren:',kb([[{text:`🏆 ${g.home}`,callback_data:`win:${gid}:${g.hid}:${g.version}`}],[{text:`🏆 ${g.away}`,callback_data:`win:${gid}:${g.aid}:${g.version}`}],[{text:'▶️ Läuft',callback_data:`live:${gid}:${g.version}`},{text:'Absagen',callback_data:`cancel:${gid}:${g.version}`}],back('Spiele','games')]))}
if(d.startsWith('win:')||d.startsWith('live:')||d.startsWith('cancel:')){const x=d.split(':'),gid=+x[1],isWin=d.startsWith('win:'),ver=+(isWin?x[3]:x[2]),winner=isWin?+x[2]:null;const r=isWin?await db.query("UPDATE games SET winner_team_id=$1,status='finished',version=version+1 WHERE id=$2 AND version=$3 RETURNING id",[winner,gid,ver]):await db.query('UPDATE games SET status=$1,winner_team_id=NULL,version=version+1 WHERE id=$2 AND version=$3 RETURNING id',[d.startsWith('live:')?'live':'cancelled',gid,ver]);if(!r.rowCount)return bot.sendMessage(m.chat.id,'⚠️ Spiel wurde zwischenzeitlich geändert.',mainMenu);if(isWin)await advanceKnockout(gid);return showGames(bot,m.chat.id)}
if(d==='ko'){const p=await qualificationPlan();if(!p.size)return bot.sendMessage(m.chat.id,'Noch nicht genug Teams.',kb([back('Hauptmenü','main')]));if(p.unresolved.length)return bot.sendMessage(m.chat.id,'Gleichstände müssen zuerst entschieden werden.',kb([...p.unresolved.map(x=>[{text:`Gruppe ${x.group}`,callback_data:`tie:${x.group}`}]),back('Hauptmenü','main')]));const fm=(await db.query('SELECT final_mode FROM settings WHERE id=1')).rows[0].final_mode;return bot.sendMessage(m.chat.id,`Empfehlung: ${p.size}er K.-o.-Runde. Finalmodus: ${fm==='bo3'?'Best of Three':'1 Spiel'}`,kb([[{text:'K.-o.-Phase erstellen',callback_data:'ko_create'}],back('Hauptmenü','main')]))}if(d==='ko_create'){const fm=(await db.query('SELECT final_mode FROM settings WHERE id=1')).rows[0].final_mode;const p=await createKnockout(fm);return bot.sendMessage(m.chat.id,`${p.size}er K.-o.-Phase erstellt.`,mainMenu)}if(d.startsWith('tie:')){const group=d.slice(4),p=await qualificationPlan(),tie=p.unresolved.find(x=>x.group===group);if(!tie)return;return begin(bot,m.chat.id,id,'knockout',{step:'tie_order',group,allowedIds:tie.teams.map(t=>t.id)},`IDs in gewünschter Reihenfolge senden:\n${tie.teams.map(t=>`${t.id}: ${t.name}`).join('\n')}`,kb([back('K.-o.-Phase','ko')]))}
}catch(e){await done(id);console.error(e);return bot.sendMessage(m.chat.id,'Aktion fehlgeschlagen.',mainMenu)}});
bot.on('message',async m=>{if(m.text?.startsWith('/start')||!ok(m))return;const s=states.get(m.from.id);if(!s)return;const t=(m.text||'').trim();try{
if(s.step==='rules_collect'){if(!m.text)return; s.plain.push(m.text);s.html.push(telegramToHtml(m.text,m.entities||[]));return bot.sendMessage(m.chat.id,`Regelteil ${s.plain.length} übernommen.`,kb([[{text:'✅ Regelwerk speichern',callback_data:'rules_save'}],[{text:'❌ Verwerfen',callback_data:'rules_cancel'}]]))}
if(s.step==='onboard_title'){s.title=t.slice(0,120);s.step='onboard_desc';return bot.sendMessage(m.chat.id,'Optionale Beschreibung oder /skip:')}
if(s.step==='onboard_desc'){s.description=t==='/skip'?'':t.slice(0,500);s.step='onboard_final';return bot.sendMessage(m.chat.id,'Finalmodus wählen:',kb([[{text:'1 Entscheidungsspiel',callback_data:'onboard_final_single'}],[{text:'Best of Three',callback_data:'onboard_final_bo3'}],[{text:'Abbrechen',callback_data:'page'}]]))}
if(s.step==='site_logo'){const logo=t==='/remove'?null:await photo(bot,m);if(t!=='/remove'&&!logo)return;await db.query('UPDATE settings SET logo=$1,version=version+1 WHERE id=1',[logo]);await done(m.from.id);return bot.sendMessage(m.chat.id,'Logo aktualisiert.',pageMenu)}if(s.step==='title'){await db.query('UPDATE settings SET title=$1,version=version+1 WHERE id=1',[t.slice(0,120)]);await done(m.from.id);return bot.sendMessage(m.chat.id,'Titel gespeichert.',textMenu)}if(s.step==='description'){await db.query('UPDATE settings SET description=$1,version=version+1 WHERE id=1',[t==='/remove'?'':t.slice(0,500)]);await done(m.from.id);return bot.sendMessage(m.chat.id,'Beschreibung gespeichert.',textMenu)}if(s.step==='ticker'){await db.query('UPDATE settings SET ticker=$1,ticker_enabled=$2,version=version+1 WHERE id=1',[t.toLowerCase()==='aus'?'':t.slice(0,500),t.toLowerCase()!=='aus']);await done(m.from.id);return bot.sendMessage(m.chat.id,'Banner aktualisiert.',textMenu)}
if(s.step==='sponsor_name'){s.name=t.slice(0,120);s.step='sponsor_logo';return bot.sendMessage(m.chat.id,'Sponsorlogo oder /skip:')}if(s.step==='sponsor_logo'){s.logo=t==='/skip'?null:await photo(bot,m);s.step='sponsor_url';return bot.sendMessage(m.chat.id,'Optionale Website oder /skip:')}if(s.step==='sponsor_url'){await db.query('INSERT INTO sponsors(name,logo,url) VALUES($1,$2,$3)',[s.name,s.logo,t==='/skip'?null:t.slice(0,500)]);await done(m.from.id);return bot.sendMessage(m.chat.id,'Sponsor hinzugefügt.',pageMenu)}
if(s.step==='team_name'){s.name=t.slice(0,100);s.step='team_group';return bot.sendMessage(m.chat.id,'Gruppe oder „-“:')}if(s.step==='team_group'){s.group=t==='-'?null:t.slice(0,40);s.step='team_logo';return bot.sendMessage(m.chat.id,'Teamlogo oder /skip:')}if(s.step==='team_logo'){const logo=t==='/skip'?null:await photo(bot,m);await db.query('INSERT INTO teams(name,group_name,logo) VALUES($1,$2,$3)',[s.name,s.group,logo]);await done(m.from.id);return showTeams(bot,m.chat.id)}if(s.step==='team_logo_edit'){const logo=t==='/remove'?null:await photo(bot,m);await db.query('UPDATE teams SET logo=$1,version=version+1 WHERE id=$2',[logo,s.teamId]);await done(m.from.id);return teamManage(bot,m.chat.id,s.teamId)}if(s.step==='group_count'){const n=+t;if(!Number.isInteger(n)||n<1||n>26)return bot.sendMessage(m.chat.id,'1 bis 26.');await assignGroups(n);await done(m.from.id);return showTeams(bot,m.chat.id)}if(s.step==='manual_group'){await db.query('UPDATE teams SET group_name=$1,rank_override=NULL,version=version+1 WHERE id=$2',[t==='-'?null:t.slice(0,40),s.teamId]);await done(m.from.id);return teamManage(bot,m.chat.id,s.teamId)}if(s.step==='tie_order'){const ids=t.split(',').map(x=>Number(x.trim())).filter(Number.isInteger);await setTieOrder(s.group,ids);await done(m.from.id);return bot.sendMessage(m.chat.id,'Reihenfolge gespeichert.',mainMenu)}
}catch(e){await done(m.from.id);console.error(e);return bot.sendMessage(m.chat.id,'Aktion fehlgeschlagen.',mainMenu)}});
bot.on('callback_query',async q=>{if(!ok(q.message,q.from))return;if(!q.data.startsWith('onboard_final_'))return;const id=q.from.id,s=states.get(id);if(!s||s.step!=='onboard_final')return;const mode=q.data.endsWith('bo3')?'bo3':'single';await db.query('UPDATE settings SET title=$1,description=$2,final_mode=$3,onboarding_done=true,version=version+1 WHERE id=1',[s.title,s.description,mode]);await done(id);await bot.answerCallbackQuery(q.id).catch(()=>{});return bot.sendMessage(q.message.chat.id,'Onboarding abgeschlossen. Farben können jetzt separat gewählt werden.',pageMenu)});
}
async function showSponsors(bot,chat){const{rows}=await db.query('SELECT id,name FROM sponsors ORDER BY sort_order,id');return bot.sendMessage(chat,rows.length?'Sponsoren verwalten:':'Noch keine Sponsoren.',kb([...rows.map(s=>[{text:`🤝 ${s.name}`,callback_data:`sponsor:${s.id}`}]),[{text:'➕ Sponsor hinzufügen',callback_data:'sponsor_add'}],back('Seite verwalten','page')]))}
async function chooseTeam(bot,chat,title,prefix){const{rows}=await db.query('SELECT id,name FROM teams WHERE NOT is_demo ORDER BY name');return bot.sendMessage(chat,title,kb([...rows.map(t=>[{text:t.name,callback_data:prefix+t.id}]),back('Teams','teams')]))}
async function teamManage(bot,chat,id){const t=(await db.query('SELECT * FROM teams WHERE id=$1 AND NOT is_demo',[id])).rows[0];if(!t)return showTeams(bot,chat);return bot.sendMessage(chat,`${t.disqualified?'⛔ ':''}${t.name}\nGruppe: ${t.group_name||'–'}`,kb([[{text:t.disqualified?'✅ DQ aufheben':'⛔ Disqualifizieren',callback_data:`team_dq:${id}`}],[{text:'✏️ Gruppe ändern',callback_data:`team_group:${id}`},{text:'🖼 Logo ändern',callback_data:`team_logo:${id}`}],back('Teams','teams')]))}
async function showTeams(bot,chat){const{rows}=await db.query('SELECT * FROM teams ORDER BY is_demo,group_name NULLS LAST,name');const summary=rows.length?rows.map(t=>`${t.is_demo?'🧪 ':''}${t.disqualified?'⛔ ':''}${t.name}${t.group_name?' · '+t.group_name:''}`).join('\n'):'Noch keine Teams.';return bot.sendMessage(chat,`Teams:\n${summary}`,kb([[{text:'➕ Team hinzufügen',callback_data:'team_add'},{text:'🛠 Team verwalten',callback_data:'team_manage'}],[{text:'🎲 Automatisch gruppieren',callback_data:'groups_auto'},{text:'✏️ Gruppe zuweisen',callback_data:'groups_manual'}],[{text:'🧩 Gruppenspiele erzeugen',callback_data:'groups_games'}],back('Hauptmenü','main')]))}
async function showGames(bot,chat){const{rows}=await db.query(`SELECT g.id,g.status,g.is_demo,h.name home,a.name away,w.name winner FROM games g JOIN teams h ON h.id=g.home_team_id JOIN teams a ON a.id=g.away_team_id LEFT JOIN teams w ON w.id=g.winner_team_id ORDER BY g.is_demo,g.round_no NULLS FIRST,g.slot_no NULLS FIRST,g.id LIMIT 100`);return bot.sendMessage(chat,rows.length?'Spiele:':'Noch keine Spiele.',kb([...rows.map(g=>[{text:`${g.is_demo?'🧪 ':''}${g.status==='live'?'▶️ LÄUFT · ':''}${g.home} vs ${g.away}${g.winner?' · 🏆 '+g.winner:''}`,callback_data:`res:${g.id}`}]),back('Hauptmenü','main')]))}
