import { db } from './db.js';
export async function assignGroups(groupCount,demo=false){const {rows}=await db.query('SELECT id FROM teams WHERE is_demo=$1 AND NOT disqualified ORDER BY random()',[demo]);const n=Math.max(1,Math.min(+groupCount||1,26)),names=Array.from({length:n},(_,i)=>String.fromCharCode(65+i));for(let i=0;i<rows.length;i++)await db.query('UPDATE teams SET group_name=$1,version=version+1 WHERE id=$2',[names[i%n],rows[i].id]);return names}
function rankGroup(teams,games){const rows=teams.map(t=>{const own=games.filter(g=>g.home_team_id===t.id||g.away_team_id===t.id),wins=own.filter(g=>g.winner_team_id===t.id).length;return{...t,played:own.length,wins,losses:own.length-wins}});rows.sort((a,b)=>{if(b.wins!==a.wins)return b.wins-a.wins;const direct=games.find(g=>((g.home_team_id===a.id&&g.away_team_id===b.id)||(g.home_team_id===b.id&&g.away_team_id===a.id))&&g.winner_team_id);if(direct)return direct.winner_team_id===a.id?-1:1;return a.name.localeCompare(b.name,'de')});return rows.map((t,i)=>({...t,place:i+1}))}
export async function standings({demo=false,includeDisqualified=true}={}){const teams=(await db.query('SELECT id,name,logo,group_name,disqualified FROM teams WHERE is_demo=$1 AND group_name IS NOT NULL ORDER BY group_name,name',[demo])).rows,games=(await db.query("SELECT group_name,home_team_id,away_team_id,winner_team_id FROM games WHERE is_demo=$1 AND phase='group' AND status='finished' AND winner_team_id IS NOT NULL",[demo])).rows;return [...new Set(teams.map(t=>t.group_name))].sort().map(group=>{const groupTeams=teams.filter(t=>t.group_name===group),active=groupTeams.filter(t=>!t.disqualified),ranked=rankGroup(active,games.filter(g=>g.group_name===group));const dq=groupTeams.filter(t=>t.disqualified).map(t=>({...t,played:games.filter(g=>g.group_name===group&&(g.home_team_id===t.id||g.away_team_id===t.id)).length,wins:0,losses:0,place:null}));return{group,teams:includeDisqualified?[...ranked,...dq]:ranked}})}
export function recommendKnockout(teamCount){const candidates=[2,4,8,16,32,64].filter(n=>n<=teamCount);if(!candidates.length)return 0;return candidates.reduce((best,n)=>Math.abs(n/teamCount-.52)<Math.abs(best/teamCount-.52)?n:best,candidates[0])}
export async function qualificationPlan(){const tables=await standings({includeDisqualified:false}),total=tables.reduce((n,g)=>n+g.teams.length,0),size=recommendKnockout(total);if(!size)return{size:0,tables,qualified:[]};const per=Math.floor(size/tables.length),qualified=[],pool=[];for(const g of tables){qualified.push(...g.teams.slice(0,per).map(t=>({...t,source:`${g.group}${t.place}`})));pool.push(...g.teams.slice(per).map(t=>({...t,source:`${g.group}${t.place}`})))}pool.sort((a,b)=>a.place-b.place||b.wins-a.wins||a.losses-b.losses||a.name.localeCompare(b.name,'de'));qualified.push(...pool.slice(0,size-qualified.length));return{size,tables,qualified}}
export async function createKnockout(finalMode='single'){const plan=await qualificationPlan();if(plan.qualified.length!==plan.size)throw new Error('not_enough_teams');await db.query("DELETE FROM games WHERE phase='knockout' AND NOT is_demo");const seeds=[...plan.qualified],pairs=[];while(seeds.length){const a=seeds.shift();let idx=seeds.findIndex(x=>x.group_name!==a.group_name);if(idx<0)idx=seeds.length-1;const b=seeds.splice(idx,1)[0];pairs.push([a,b])}const label=plan.size===2?'Finale':plan.size===4?'Halbfinale':plan.size===8?'Viertelfinale':plan.size===16?'Achtelfinale':`Runde der ${plan.size}`;for(const [a,b] of pairs)await db.query("INSERT INTO games(phase,round_label,home_team_id,away_team_id) VALUES('knockout',$1,$2,$3)",[label,a.id,b.id]);await db.query('UPDATE settings SET final_mode=$1,knockout_size=$2,tournament_finished=false,winner_team_id=NULL,version=version+1 WHERE id=1',[finalMode,plan.size]);return plan}
export async function seedDemo(){const c=await db.connect();try{await c.query('BEGIN');await c.query('DELETE FROM games WHERE is_demo');await c.query('DELETE FROM teams WHERE is_demo');const names=['Becherblitze','Flaschenfreunde','Zielwasser','Wurfwunder','Kronkorken Crew','Durstlöscher','Dosenjäger','Treffertruppe'],ids=[];for(let i=0;i<8;i++){const r=await c.query('INSERT INTO teams(name,group_name,is_demo) VALUES($1,$2,true) RETURNING id',[names[i],i<4?'A':'B']);ids.push(r.rows[0].id)}for(const [a,b,g,w] of [[0,1,'A',0],[2,3,'A',3],[0,2,'A',2],[1,3,'A',1],[4,5,'B',4],[6,7,'B',7],[4,6,'B',4],[5,7,'B',7]])await c.query("INSERT INTO games(group_name,phase,home_team_id,away_team_id,winner_team_id,status,is_demo) VALUES($1,'group',$2,$3,$4,'finished',true)",[g,ids[a],ids[b],ids[w]]);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
export async function clearDemo(){await db.query('DELETE FROM games WHERE is_demo');await db.query('DELETE FROM teams WHERE is_demo')}
